import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Download, Copy, FileText, Scale } from 'lucide-react';
import { ResearchResult } from '../lib/types';

interface ExportBriefModalProps {
    isOpen: boolean;
    onClose: () => void;
    query: string;
    results: ResearchResult[];
}

export const ExportBriefModal: React.FC<ExportBriefModalProps> = ({ isOpen, onClose, query, results }) => {
    if (!isOpen) return null;

    const briefContent = `
CASE BRIEF FOR ADVOCATE REVIEW
Generated by NyayaFlow AI
------------------------------
DATE: ${new Date().toLocaleDateString()}
CLIENT QUERY: "${query}"

PRELIMINARY AI FINDINGS:
${results?.[0]?.summary || "Analysis indicates potential legal risks."}

KEY AUTHORITIES CITED:
${results?.[0]?.citation || "N/A"}

RISK ASSESSMENT:
High Priority - Requires Professional Legal Opinion.
`;

    const handleCopy = () => {
        navigator.clipboard.writeText(briefContent);
        // Toast logic here if needed
    };

    const handleDownload = () => {
        const blob = new Blob([briefContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Case_Brief_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        onClose();
    };

    return (
        <AnimatePresence>
            <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="bg-white dark:bg-zinc-900 rounded-2xl shadow-xl w-full max-w-lg border border-zinc-200 dark:border-zinc-800"
                >
                    <div className="p-6 border-b border-zinc-100 dark:border-zinc-800 flex justify-between items-center">
                        <div className="flex items-center gap-3">
                            <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg text-blue-600 dark:text-blue-400">
                                <Scale className="w-5 h-5" />
                            </div>
                            <div>
                                <h3 className="text-lg font-semibold text-zinc-900 dark:text-white">Export Case Brief</h3>
                                <p className="text-xs text-zinc-500">Prepare for your lawyer consultation</p>
                            </div>
                        </div>
                        <button onClick={onClose} className="p-2 hover:bg-zinc-100 dark:hover:bg-zinc-800 rounded-full transition-colors">
                            <X className="w-5 h-5 text-zinc-500" />
                        </button>
                    </div>

                    <div className="p-6 space-y-4">
                        <div className="bg-zinc-50 dark:bg-zinc-950 p-4 rounded-xl border border-zinc-200 dark:border-zinc-800 text-sm font-mono text-zinc-600 dark:text-zinc-400 max-h-60 overflow-y-auto whitespace-pre-wrap">
                            {briefContent}
                        </div>

                        <p className="text-xs text-zinc-500 italic">
                            This brief summarizes your query and the AI's preliminary findings to save time during your legal consultation.
                        </p>
                    </div>

                    <div className="p-6 border-t border-zinc-100 dark:border-zinc-800 flex gap-3">
                        <button
                            onClick={handleCopy}
                            className="flex-1 px-4 py-2.5 rounded-xl border border-zinc-200 dark:border-zinc-700 text-zinc-700 dark:text-zinc-300 font-medium hover:bg-zinc-50 dark:hover:bg-zinc-800 transition-colors flex items-center justify-center gap-2"
                        >
                            <Copy className="w-4 h-4" />
                            Copy Text
                        </button>
                        <button
                            onClick={handleDownload}
                            className="flex-1 px-4 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-medium transition-colors flex items-center justify-center gap-2 shadow-lg shadow-blue-500/20"
                        >
                            <Download className="w-4 h-4" />
                            Download PDF
                        </button>
                    </div>
                </motion.div>
            </div>
        </AnimatePresence>
    );
};
